try {
  let a;
  console.log(a.length);
  console.log("Hi I am inside try block");
} catch (error) {
  console.log("Hi I am inside catch block");
}

console.log("Hi I am outside try-catch block");
